# baseURL: https://amethyst.bencuan.me
theme: 
  - amethyst

# Book configuration
disablePathToLower: true

security:
  enableInlineShortcodes: 

sitemap:
  changeFreq: ""
  disable: false
  filename: sitemap.xml
  priority: -1